version: '3.9'

services:
    db:
        image: postgres
        environment:
            TZ: America/Detroit
            POSTGRES_DB: finance
            POSTGRES_USER: finance
            POSTGRES_PASSWORD: finance
        ports:
            - 5432:5432
    web:
        build:
            context: .
            args:
                TZ: America/Detroit
        command: [
            "--log-level=debug",
            "--access-logformat=%(t)s %(h)s %(a)s %(r)s %(s)s %(b)s",
            "--access-logfile=-",
            "--log-file=-",
            "--reload",
            "--keyfile", "finance.key",
            "--certfile", "finance.crt"
        ]
        environment:
            FLASK_KEY: finance
            DB_HOST: db
            DB_NAME: finance
            DB_USER: finance
            DB_PASSWORD: finance
        volumes:
            - .:/app
        ports:
            - 443:5000